### ISSUE TITLE
Instructions to build QUIC Spec version of Ivy not complete

### ISSUE THREAD

**Issue by silverbucket** [microsoft/ivy#93]
I'm able to build IVy using the master branch, however for QUIC testing it's mentioned to use specifically the `quic15_merge_temp` branch:
https://github.com/microsoft/ivy/blob/quic15_merge_temp/doc/examples/quic/README.md#installation-steps

However, when using this branch, and following the linked install instructions, I can't get by the first step:

```
# python build_submodules.py
python: can't open file 'build_submodules.py': [Errno 2] No such file or directory
# find . -name "build_submodules.py"
#
```

**Comment by kenmcmil** [comment]
Sorry, the current QUIC tester version is on branch `quic23`.

Can you let me know where you found the instructions to use `quic15_merge_temp` so I can update it?

Thanks.

**Comment by silverbucket** [comment]
@kenmcmil thanks, that seems to be working, building now. The mention of the temp branch is in the first sentence of the installation instructions here: https://github.com/microsoft/ivy/blob/quic15_merge_temp/doc/examples/quic/README.md#installation-steps

**Comment by silverbucket** [comment]
@kenmcmil continuing along this thread, I'm still following the instructions, build `core` and `picotls` and am trying to add the `picotls` package using `ivy_libs` however it's failing.
```
~/ietf/ivy# ivy_libs add picotls ../picotls/
Adding library picotls at prefix ../picotls/.
Traceback (most recent call last):
  File "/usr/local/bin/ivy_libs", line 11, in <module>
    load_entry_point('ms-ivy==0.3', 'console_scripts', 'ivy_libs')()
  File "/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/ivy_libs.py", line 64, in main
    with open(specfilename,"w") as out:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/lib/specs'
~/ietf/ivy# ls /usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/
EGG-INFO  ivy
#
```

**Comment by kenmcmil** [comment]
Sorry, those instructions are out of date. The picotls library is now a submodule of Ivy, so it is built when you run `build_submodules`. The directions in the section 'Picotls' are no longer needed.

**Comment by kenmcmil** [comment]
Fixed in commit 2d55399.

**Comment by silverbucket** [comment]
Thanks for the help in getting this built so far. I've moved further along and am now trying to "Build the server tester" ... I installed `libz3-dev` but am still encountering a build failure:
```
~/ietf/ivy/doc/examples/quic# ivyc target=test quic_server_test_stream.ivy
g++  -I /usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/include -L /usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/lib -Wl,-rpath=/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/lib -g -o quic_server_test_stream quic_server_test_stream.cpp -lz3 -lpicotls-core -lpicotls-minicrypto -lpicotls-openssl -lssl -lcrypto -ldl -pthread
/tmp/ccOPfB2s.o: In function `z3::context::string_val(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/include/z3++.h:2586: undefined reference to `Z3_mk_string'
/tmp/ccOPfB2s.o: In function `gen::eval_string[abi:cxx11](z3::expr const&)':
/root/ietf/ivy/doc/examples/quic/build/quic_server_test_stream.cpp:267: undefined reference to `Z3_is_string'
/root/ietf/ivy/doc/examples/quic/build/quic_server_test_stream.cpp:268: undefined reference to `Z3_get_string'
collect2: error: ld returned 1 exit status
#
```

**Comment by silverbucket** [comment]
> Sorry, the current QUIC tester version is on branch `quic23`.
> 
> Can you let me know where you found the instructions to use `quic15_merge_temp` so I can update it?
> 
> Thanks.

@kenmcmil  Ah also, to answer your question, the original link to that branch was from an email to the QUIC working group back in Nov 2018, which explains the old branch reference. Going forward, is it safe to assume the QUIC-related stuff will be on the `quic*` branch named with the highest number?

**Comment by kenmcmil** [comment]
Hmmm. It looks like the Z3 header that Ivy is using doesn't match the library. Did you run `build_submodules` and then `python setup.py install`? Ivy should use its own Z3 library and not the one (if any) installed in the system. Make sure there is a `libz3.so` in `/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/lib`.

Yes, you should be able to find the tester for QUIC draft-XX in branch quicXX.  At this point the tester is only up to draft 23.

**Comment by silverbucket** [comment]
@kenmcmil I did follow that process, however there is no `libz3.so` in `/usr/local/lib/python2.7/dist-packages/ms_ivy-0.3-py2.7.egg/ivy/lib` ... it does exist several places within the repo workspace though:

```
~/ietf/ivy/doc/examples/quic# find . -name "libz3.so"
./ivy/z3/libz3.so
./ivy/z3/lib/libz3.so
./ivy/lib/libz3.so
./submodules/z3/build/libz3.so
./submodules/z3/build/python/libz3.so
./build/lib.linux-x86_64-2.7/ivy/z3/libz3.so
./lib/libz3.so
```

So I copied it over manually. Perhaps I could have appended my PYTHONPATH but I'm not sure why it didn't install it in the system.

Thanks for the help, I will close this ticket now.

**Comment by kenmcmil** [comment]
It looks like a bug in the install process. I'll try to track it down. Meanwhile, try using `python setup.py develop`, which is what I normally use. That installs via symlinks, which is better, because you can just `git pull` to get the latest code without re-installing.

**Comment by kenmcmil** [comment]
Looks like there was a patch to `setup.py` that didn't make it from the master branch to the quic23 branch. I think that is fixed in commit 84a6b95.
